#!/usr/bin/env python

# -*- coding: UTF8 -*-

### Copyright (C) 2008 Antonio Valentino <a_valentino@users.sf.net>

### This file is part of GSDView.

### GSDView is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; either version 2 of the License, or
### (at your option) any later version.

### GSDView is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.

### You should have received a copy of the GNU General Public License
### along with GSDView; if not, write to the Free Software
### Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.

'''Launcher script for gsdview.'''

import datetime

class Timer(object):
    def __init__(self):
        self.start = datetime.datetime.now()
        self.last = self.start

    def elapsed(self):
        return datetime.datetime.now() - self.start

    def update(self):
        now = datetime.datetime.now()
        delta = now - self.last
        self.last = now
        return delta.seconds, delta.microseconds

t = Timer()

import logging
fmt = '%(levelname)s: %(filename)s line %(lineno)d in %(funcName)s: %(message)s'
logging.basicConfig(level=logging.DEBUG, format=fmt)

logging.debug('logging setup done after %d.%06ds: start logging' % t.update())

import os
import sys
import logging

logging.debug('stdlib imports: %d.%06ds' % t.update())

import numpy

logging.debug('numpy import: %d.%06ds' % t.update())

import scipy

logging.debug('scipy import: %d.%06ds' % t.update())

try:
    from osgeo import gdal, osr
except ImportError:
    import gdal, osr

logging.debug('gdal/osr import %d.%06ds' % t.update())

from PyQt4 import QtCore, QtGui

logging.debug('Qt4 import %d.%06ds' % t.update())


#~ import sys
from gsdview.gsdview import main

logging.debug('gsdview import %d.%06ds' % t.update())

sys.exit(main())
