# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

GSDVIEWROOT = os.path.abspath(os.path.join(os.pardir, os.pardir))
sys.path.insert(0, GSDVIEWROOT)
sys.path.insert(1, os.path.join(GSDVIEWROOT, 'gsdview', 'plugins'))


# -- Project information -----------------------------------------------------

project = 'GSDView'
copyright = '2018-2019, Antonio Valentino'
author = 'Antonio Valentino'

from gsdview.info import version as RELEASE

# The short X.Y version
version = '.'.join(RELEASE.split('.')[:2])
# The full version, including alpha/beta/rc tags
release = RELEASE


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    # 'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    # 'sphinx.ext.coverage',
    'sphinx.ext.imgmath',
    # 'sphinx.ext.jsmath',
    # 'sphinx.ext.graphviz',
    # 'sphinx.ext.inheritance_diagram',
    # 'sphinx.ext.refcounting',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.extlinks',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['latestnews.txt']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sourceforge'
# html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'collapsiblesidebar': True,
    'unixname': 'gsdview',
    'groupid': '226458',
    # 'allura_wiki': True,
    # 'allura_news': False,
    # 'allura_code': True,
    # 'allura_tickets': True,
    # 'allura_mailinglist': True,
    'extralinks': [
        # ('GSDView Pro', 'http://www.consorzio-innova.com/static/gsdview/index.html'),
        ('GitHub project site', 'https://github.com/avalentino/gsdview'),
        ('Wiki', 'https://github.com/avalentino/gsdview/wiki'),
        ('Issue tracker', 'https://github.com/avalentino/gsdview/issues'),
    ],
}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['../themes']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = 'GSDView Open Edition'

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = 'GSDView'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '_static/logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/logo.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
html_sidebars = {
    'index': ['localtoc.html', 'relations.html', 'sourcelink.html',
              'sfpagesidebar.html', 'searchbox.html', 'ohlohsidebar.html'],
}

# If false, no index is generated.
html_use_index = False


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'GSDViewdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '12pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'GSDView.tex', 'GSDView Documentation',
     'Antonio Valentino', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'images/logo_large.pdf'


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('manpage', 'gsdview', 'Geo-spatial data viewer',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'GSDView', 'GSDView Documentation',
     author, 'GSDView', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = 'GSDView Open Edition'

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3',
               '/usr/share/doc/python3/html/objects.inv'),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for autodoc extension -------------------------------------------

autoclass_content = 'both'
autodoc_default_flags = ['members', 'undoc-members', 'show-inheritance']
                        # ,'inherited-members']

# -- Options for autosummary extension ---------------------------------------

autosummary_generate = ['reference']


# -- Options for external links extension ------------------------------------
extlinks = {'issue': ('https://github.com/avalentino/gsdview/issues/%s', '#')}
